### ISSUE TITLE
Different results between SpliceAI 1.3.1 on our cluster versus Broad web version

### ISSUE THREAD

**Issue by cpsosa** [broadinstitute/SpliceAI-lookup#9]
Hi,

I am running a version of SpliceAI 1.3.1 installed on our cluster and comparing the results to my run using the BROAD web version. The first two rows of the table below show perfect match. However, the last two rows on the cluster DP_AL is 25 and DP_DG is 26. The web version does not provide any value.

Do you know why there is a difference in selected cases? The issue for all the variants that I have tested seem to appear only for the pre-mRNA position.

I am using all defaults in both cases including hg19.

Thanks

         | Variant | ALLELE | SYMBOL | DS_AG | DS_AL | DS_DG | DS_DL | DP_AG | DP_AL | DP_DG | DP_DL
Cluster | 1-94488942-C-T | T | ABCA4 | 0 | 0.71 | 0 | 0.55 | 0 | 32 | 32 | 0
Web | 1-94488942-C-T | T | ABCA4 | 0 | 0.71 | 0 | 0.55 | | 32 | | 0
Cluster | 1-94470997-C-T | T | ABCA4 | 0 | 0 | 0 | 0.97 | 0 | 25 | 26 | 0
Web | 1-94470997-C-T | T | ABCA4 | 0 | 0 | 0 | 0.97 | | | | 0

Please let me know if you need additional information.

**Comment by bw2** [comment]
Hi @cpsosa , the server is also using SpliceAI v1.3.1, and pre-computed scores downloaded from Illumina BaseSpace ~1 year ago. The vcf files that contain the precomputed scores have this header line:
```
##fileDate=20191004
```
Also, are you using masked or raw scores?
If none of this explains the issue, can you please share the SpliceAI-lookup url you're using to get the scores? 
This will tell me the full set of parameters.

**Comment by cpsosa** [comment]
[SpliceAILookup.pdf](https://github.com/broadinstitute/SpliceAI-lookup/files/6644956/SpliceAILookup.pdf)

Please let me know if you can open this file.  Otherwise I'll try to send it again.  Defaults being used.  hg19, raw scores, pre-computed scores no.

**Comment by cpsosa** [comment]
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20191004
##reference=GRCh37/hg19
##contig=<ID=1,length=249250621>

Yes, it has that date.

Carlos P. Sosa, Ph.D.
Assistant Professor of Biomedical Informatics, College of Medicine
Informatics Specialist Lead
Clinical Genome Sequencing Laboratory(CGSL), Department of Laboratory
Medicine and Pathology
Mayo Clinic 200 First Street SW | Rochester, MN 55905

**Comment by bw2** [comment]
Thanks for providing the additional info. One thing I'm still confused about is where you see this text
```
Web | 1-94470997-C-T | T | ABCA4 | 0 | 0 | 0 | 0.97 | | | | 0
```
In the web version, the server returns the distances (you can see them in the API response here:
https://spliceailookup-api.broadinstitute.org/spliceai/?hg=37&distance=50&mask=0&precomputed=0&variant=1-94470997-C-T&raw=1-94470997-C-T)

but the client-side code hides the distance if the corresponding delta score is 0 (you can see this logic here:
https://github.com/broadinstitute/SpliceAI-lookup/blob/master/index.html#L520-L526 ).
I added this to make the output table easier to read. 
Is there a use-case where you want to see distances even if the delta score == 0?

Ps. I just fixed the sort order for this example so that the canonical transcript is first.

**Comment by cpsosa** [comment]
Hi,

Thank you for your reply.  I see that the output from the API has the
distance.

Web | 1-94470997-C-T | T | ABCA4 | 0 | 0 | 0 | 0.97 | | | | 0


This came from your website, I simply put the table in the website in
the format that spliceai uses in the VCF file.

Were you able to see the PDF I sent?  There I do not see 25 & 26.
They are in the API output you sent.


Thanks

**Comment by cpsosa** [comment]
I also tried using chrome but I still do not see 25 and 26 pre-mRNA
positions as reported by the cluster version.

Cluster:

##INFO=<ID=SpliceAI,Number=.,Type=String,Description="SpliceAIv1.3.1
variant annotation. These include delta scores (DS) and delta positions
(DP) for acceptor gain (AG), acceptor loss (AL), donor gain (DG), and donor
loss (DL). Format:
ALLELE|SYMBOL|DS_AG|DS_AL|DS_DG|DS_DL|DP_AG|DP_AL|DP_DG|DP_DL">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       94522386        .       C       T       .       .
SpliceAI=T|ABCA4|0.68|0.66|0.00|0.00|-2|-8|-8|-16
1       94488942        .       C       T       .       .
SpliceAI=T|ABCA4|0.00|0.71|0.00|0.55|0|32|32|0
1       94474432        .       A       C       .       .
SpliceAI=C|ABCA4|0.99|0.09|0.00|0.00|-1|-5|-5|-23
1       94470997        .       C       T       .       .
SpliceAI=T|ABCA4|0.00|0.00|0.00|0.97|0|25|26|0
.
.
.

**Comment by bw2** [comment]
I did open the pdf. 
The website intentionally hides the 25 & 26 values because their corresponding delta scores = 0

**Comment by cpsosa** [comment]
Thank you.  This clarifies the difference.
